int8 motor_id            # Motor ID (0-255)
uint8 control_mode       # Mode (0: operation, 1: position, 2: speed, 3: current, 4: enable, 5: disable, 6:SetParam)
string param_name
uint8 communication_type # Communication type (8: Table, 18:General ITEM)
float32 param_value      # General parameter value
float32 cur_kp           # Current PID proportional gain of MIT mode
float32 cur_ki           # Current PID Integral gain of MIT mode   
float32 spd_kp           # Speed PID proportional gain of Speed and Location mode
float32 spd_ki           # Speed PID Integral gain of Speed and Location mode
float32 loc_kp           # Location PID proportional gain of Location mode
float32 spd_filt_gain    # Speed filter parameters
float32 limit_spd        # Location mode         speed limit
float32 limit_cur        # Position, Speed mode  current limit
---
bool success
string message 