can:
  interface: "canalystii"
  # interface: "socketcan"
  channel: 0
  bitrate: 1000000

motors:
# Left Leg
  - id: 1
    limit_spd: 3.0
    limit_cur: 3.0
    control_mode: 0 
    max_distance: 3.0
    # raw_pos_zero: 1.0295047303133003
    # raw_pos_zero: 1.308686129145998
    raw_pos_zero: 1.5707963268
    flip: True
    mit:
      kp: 5.0
      kd: 0.5

  - id: 2
    limit_spd: 3.0
    limit_cur: 3.0
    control_mode: 0 
    max_distance: 3.0
    # raw_pos_zero: 1.0295047303133003
    # raw_pos_zero: 1.308686129145998
    raw_pos_zero: 1.5707963268
    flip: True
    mit:
      kp: 5.0
      kd: 0.5